SELECT
       NAME,
       EARNINGS,
       SPORT,
       AVG(EARNINGS) OVER (PARTITION BY SPORT) AS SPORT_AVG,
       YEAR,
       AVG(EARNINGS) OVER (PARTITION BY YEAR)  AS YEAR_AVG
FROM
     TOP_ATHLETES
ORDER BY
    SPORT;


WITH rankings AS (
SELECT
    NAME,
    EARNINGS,
    YEAR,
    SPORT,
    ROW_NUMBER() OVER(PARTITION BY SPORT, YEAR ORDER BY EARNINGS DESC) AS YEARLY_SPORT_RANK
FROM
    TOP_ATHLETES
ORDER BY
    YEAR DESC,
    EARNINGS DESC)

SELECT
    NAME,
    EARNINGS,
    YEAR,
    SPORT
FROM rankings
WHERE
    YEARLY_SPORT_RANK = 1;