SELECT
       NAME,
       EARNINGS,
       SPORT,
       AVG(EARNINGS) OVER (PARTITION BY SPORT) AS SPORT_AVG,
       YEAR,
       AVG(EARNINGS) OVER (PARTITION BY YEAR)  AS YEAR_AVG
FROM
     TOP_ATHLETES
ORDER BY
    SPORT;


WITH rankings AS (
SELECT
    NAME,
    EARNINGS,
    YEAR,
    SPORT,
    ROW_NUMBER() OVER(PARTITION BY SPORT, YEAR ORDER BY EARNINGS DESC) AS YEARLY_SPORT_RANK
FROM
    TOP_ATHLETES
ORDER BY
    YEAR DESC,
    EARNINGS DESC)

SELECT
    NAME,
    EARNINGS,
    YEAR,
    SPORT
FROM rankings
WHERE
    YEARLY_SPORT_RANK = 1;

WITH yearly_rank AS (
    SELECT
        YEAR,
        NAME,
        EARNINGS,
        ROW_NUMBER() over (PARTITION BY YEAR ORDER BY EARNINGS DESC) AS year_rank
    FROM
        TOP_ATHLETES
)

SELECT
    YEAR,
    NAME,
    EARNINGS
FROM
    yearly_rank
WHERE
    year_rank = 1
ORDER BY
    YEAR DESC;

SELECT
    NAME,
    EARNINGS
FROM
    TOP_ATHLETES;
